# Generated by Django 3.1.5 on 2021-04-02 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('especialidade', models.CharField(choices=[('C01', 'Cardiologia'), ('D01', 'Dermatologia'), ('I01', 'Infectologia'), ('O01', 'Oftalmologia'), ('P01', 'Pediatria'), ('R01', 'Radioterapia')], max_length=12)),
                ('horario_disponiveis', multiselectfield.db.fields.MultiSelectField(choices=[('T01', '13:30'), ('M01', '09:30'), ('T02', '17:00'), ('T03', '19:00'), ('M02', '10:30'), ('M03', '07:00')], default=('T01', '13:30'), max_length=23, unique=True)),
                ('data_disponiveis', multiselectfield.db.fields.MultiSelectField(choices=[('D01', datetime.date(2021, 3, 17)), ('D02', datetime.date(2021, 3, 10)), ('D03', datetime.date(2021, 3, 12)), ('D04', datetime.date(2021, 3, 1)), ('D05', datetime.date(2021, 3, 3)), ('D06', datetime.date(2021, 3, 5)), ('D07', datetime.date(2021, 3, 25))], default=('D01', datetime.date(2021, 3, 17)), max_length=23, unique=True)),
                ('crm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anonymus', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', multiselectfield.db.fields.MultiSelectField(choices=[('D01', datetime.date(2021, 3, 17)), ('D02', datetime.date(2021, 3, 10)), ('D03', datetime.date(2021, 3, 12)), ('D04', datetime.date(2021, 3, 1)), ('D05', datetime.date(2021, 3, 3)), ('D06', datetime.date(2021, 3, 5)), ('D07', datetime.date(2021, 3, 25))], default=('D01', datetime.date(2021, 3, 17)), max_length=23, unique=True)),
                ('horario_disponiveis', multiselectfield.db.fields.MultiSelectField(choices=[('T01', '13:30'), ('M01', '09:30'), ('T02', '17:00'), ('T03', '19:00'), ('M02', '10:30'), ('M03', '07:00')], default=('T01', '13:30'), max_length=23, unique=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
            ],
        ),
    ]
