# Generated by Django 3.1.5 on 2021-04-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('C01', 'Cardiologia'), ('D01', 'Dermatologia'), ('I01', 'Infectologia'), ('O01', 'Oftalmologia'), ('P01', 'Pediatria'), ('R01', 'Radioterapia')], max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidade'),
        ),
    ]
