# Generated by Django 3.1.5 on 2021-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210402_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
