# Generated by Django 3.1.5 on 2021-04-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210402_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.especialidade'),
            preserve_default=False,
        ),
    ]
